
services:
  app:
    build:
      context: ./backend
    container_name: warikan_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: warikan_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: warikan
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  pgdata:

